name: Feature Request
description: Request a Feature
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request
  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if an feature request already exists for the bug you encountered.
      options:
      - label: I have searched the feature requests
        required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Description of the feature
      description: Tell us what you feature you want to see. Please be descriptive with examples if any
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Reason why you want to see it on the platform
      description: Reasons.
      placeholder: Write reason here
    validations:
      required: true
  - type: dropdown
    id: versions
    attributes:
      label: Which version of the app are you using?
      description: If this issue is occurring on more than 1 version of the app, select the appropriate versions.
      multiple: true
      options:
       - 1.0.0
       - 1.1.0
       - 1.2.0
       - 2.0.0
       - 2.1.0
    validations:
      required: true
